### ISSUE TITLE
Merge Server-Sent-Event & WebSocket into one server

### ISSUE THREAD

**Issue by kalitine** [coast-team/sigver#15]
**Current behavior**
There are two files: `src/SseServer.js` and `src/WsServer.js`. User can only run them separately (must be different ports).

**Expected behavior**
Use one HTTP server for both (one port in use).

**What is the motivation / use case for changing the behavior?**
Improve project maintainability and usability (as only one port is needed). In case of `uws` improve also performance.

**Solution**
Consider to use [uws](https://github.com/uWebSockets/uWebSockets) for this server. In case of WebSocket the HTTP request should be upgraded.

**Comment by Conaclos** [comment]
We no longer use Server-Sent-Event. Thus this issue is no longer relevant.
